version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
  open-pull-requests-limit: 10
  target-branch: develop
  reviewers:
  - drizzer14
  ignore:
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.8
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.15
    - 7.13.8
  - dependency-name: "@babel/cli"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.0
    - 7.13.10
    - 7.13.14
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@types/jest"
    versions:
    - 26.0.20
    - 26.0.21
  - dependency-name: ts-jest
    versions:
    - 26.4.4
    - 26.5.0
    - 26.5.1
    - 26.5.2
    - 26.5.3
    - 26.5.4
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.1
    - 17.0.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: lodash
    versions:
    - 4.17.20
